import { createContext, useContext } from 'react';

// Folder definitions for ThemePanel
export const themeFolders = [
  { id: 'all',       label: 'All Themes', emoji: '✦' },
  { id: 'dark-pro',  label: 'Dark Pro',   emoji: '🌑' },
  { id: 'light',     label: 'Light',      emoji: '☀️' },
  { id: 'neon-cyber',label: 'Neon',       emoji: '⚡' },
  { id: 'nature',    label: 'Nature',     emoji: '🌿' },
  { id: 'editorial', label: 'Editorial',  emoji: '📖' },
  { id: 'gradient',  label: 'Gradient',   emoji: '🎨' },
];

export const themes = [
  // ─── Dark Pro ───────────────────────────────────────────────────────────────
  {
    id: 'midnight',
    name: 'Midnight',
    emoji: '🌑',
    folder: 'dark-pro',
    category: 'dark',
    preview: ['#0f172a', '#6366f1', '#8b5cf6'],
    fontHeading: 'Space Grotesk',
    fontBody: 'Inter',
    colors: {
      bg: '#0f172a',
      surface: '#1e293b',
      surfaceHover: '#283548',
      primary: '#6366f1',
      primaryFg: '#ffffff',
      secondary: '#8b5cf6',
      accent: '#06b6d4',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      textSubtle: '#475569',
      border: '#334155',
      cardBg: '#1e293b',
      gradient: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
      gradientText: 'linear-gradient(90deg, #6366f1, #06b6d4)',
    },
  },
  // ─── Light & Airy ────────────────────────────────────────────────────────────
  {
    id: 'ocean',
    name: 'Ocean',
    emoji: '🌊',
    folder: 'light',
    category: 'light',
    preview: ['#eff6ff', '#3b82f6', '#06b6d4'],
    fontHeading: 'Plus Jakarta Sans',
    fontBody: 'Inter',
    colors: {
      bg: '#eff6ff',
      surface: '#ffffff',
      surfaceHover: '#dbeafe',
      primary: '#3b82f6',
      primaryFg: '#ffffff',
      secondary: '#06b6d4',
      accent: '#10b981',
      text: '#0f172a',
      textMuted: '#475569',
      textSubtle: '#94a3b8',
      border: '#bfdbfe',
      cardBg: '#ffffff',
      gradient: 'linear-gradient(135deg, #3b82f6 0%, #06b6d4 100%)',
      gradientText: 'linear-gradient(90deg, #3b82f6, #10b981)',
    },
  },
  // ─── Nature ───────────────────────────────────────────────────────────────────
  {
    id: 'forest',
    name: 'Forest',
    emoji: '🌲',
    folder: 'nature',
    category: 'dark',
    preview: ['#052e16', '#22c55e', '#84cc16'],
    fontHeading: 'DM Sans',
    fontBody: 'DM Sans',
    colors: {
      bg: '#052e16',
      surface: '#14532d',
      surfaceHover: '#166534',
      primary: '#22c55e',
      primaryFg: '#052e16',
      secondary: '#84cc16',
      accent: '#06b6d4',
      text: '#f0fdf4',
      textMuted: '#86efac',
      textSubtle: '#4ade80',
      border: '#166534',
      cardBg: '#14532d',
      gradient: 'linear-gradient(135deg, #22c55e 0%, #84cc16 100%)',
      gradientText: 'linear-gradient(90deg, #22c55e, #06b6d4)',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    emoji: '🌅',
    folder: 'nature',
    category: 'light',
    preview: ['#fff7ed', '#f97316', '#ec4899'],
    fontHeading: 'Outfit',
    fontBody: 'Inter',
    colors: {
      bg: '#fff7ed',
      surface: '#ffffff',
      surfaceHover: '#ffedd5',
      primary: '#f97316',
      primaryFg: '#ffffff',
      secondary: '#ec4899',
      accent: '#a855f7',
      text: '#1c1917',
      textMuted: '#57534e',
      textSubtle: '#a8a29e',
      border: '#fed7aa',
      cardBg: '#ffffff',
      gradient: 'linear-gradient(135deg, #f97316 0%, #ec4899 100%)',
      gradientText: 'linear-gradient(90deg, #f97316, #a855f7)',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    emoji: '💻',
    folder: 'dark-pro',
    category: 'dark',
    preview: ['#272822', '#f92672', '#a6e22e'],
    fontHeading: 'JetBrains Mono',
    fontBody: 'JetBrains Mono',
    colors: {
      bg: '#272822',
      surface: '#3e3d32',
      surfaceHover: '#49483e',
      primary: '#f92672',
      primaryFg: '#f8f8f2',
      secondary: '#a6e22e',
      accent: '#66d9e8',
      text: '#f8f8f2',
      textMuted: '#75715e',
      textSubtle: '#49483e',
      border: '#49483e',
      cardBg: '#3e3d32',
      gradient: 'linear-gradient(135deg, #f92672 0%, #a6e22e 100%)',
      gradientText: 'linear-gradient(90deg, #f92672, #66d9e8)',
    },
  },
  // ─── Editorial ────────────────────────────────────────────────────────────────
  {
    id: 'lavender',
    name: 'Lavender',
    emoji: '💜',
    folder: 'editorial',
    category: 'light',
    preview: ['#f5f3ff', '#7c3aed', '#c026d3'],
    fontHeading: 'Plus Jakarta Sans',
    fontBody: 'Inter',
    colors: {
      bg: '#f5f3ff',
      surface: '#ffffff',
      surfaceHover: '#ede9fe',
      primary: '#7c3aed',
      primaryFg: '#ffffff',
      secondary: '#c026d3',
      accent: '#0ea5e9',
      text: '#1e1b4b',
      textMuted: '#4c1d95',
      textSubtle: '#8b5cf6',
      border: '#ddd6fe',
      cardBg: '#ffffff',
      gradient: 'linear-gradient(135deg, #7c3aed 0%, #c026d3 100%)',
      gradientText: 'linear-gradient(90deg, #7c3aed, #0ea5e9)',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    emoji: '❄️',
    folder: 'editorial',
    category: 'dark',
    preview: ['#2e3440', '#5e81ac', '#88c0d0'],
    fontHeading: 'Inter',
    fontBody: 'Inter',
    colors: {
      bg: '#2e3440',
      surface: '#3b4252',
      surfaceHover: '#434c5e',
      primary: '#88c0d0',
      primaryFg: '#2e3440',
      secondary: '#5e81ac',
      accent: '#a3be8c',
      text: '#eceff4',
      textMuted: '#d8dee9',
      textSubtle: '#4c566a',
      border: '#4c566a',
      cardBg: '#3b4252',
      gradient: 'linear-gradient(135deg, #5e81ac 0%, #88c0d0 100%)',
      gradientText: 'linear-gradient(90deg, #5e81ac, #a3be8c)',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    emoji: '◻️',
    folder: 'light',
    category: 'light',
    preview: ['#ffffff', '#171717', '#f5f5f5'],
    fontHeading: 'Inter',
    fontBody: 'Inter',
    colors: {
      bg: '#ffffff',
      surface: '#fafafa',
      surfaceHover: '#f5f5f5',
      primary: '#171717',
      primaryFg: '#ffffff',
      secondary: '#525252',
      accent: '#171717',
      text: '#171717',
      textMuted: '#525252',
      textSubtle: '#a3a3a3',
      border: '#e5e5e5',
      cardBg: '#fafafa',
      gradient: 'linear-gradient(135deg, #171717 0%, #525252 100%)',
      gradientText: 'linear-gradient(90deg, #171717, #525252)',
    },
  },
  // ─── Neon & Cyber ──────────────────────────────────────────────────────────────
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    emoji: '🌆',
    folder: 'neon-cyber',
    category: 'dark',
    preview: ['#0d0221', '#ff0090', '#00fff9'],
    fontHeading: 'Rajdhani',
    fontBody: 'Share Tech Mono',
    colors: {
      bg: '#0d0221',
      surface: '#130031',
      surfaceHover: '#1a0040',
      primary: '#ff0090',
      primaryFg: '#ffffff',
      secondary: '#00fff9',
      accent: '#f9f002',
      text: '#f0f0f8',
      textMuted: '#9090c0',
      textSubtle: '#404060',
      border: '#2d0060',
      cardBg: '#130031',
      gradient: 'linear-gradient(135deg, #ff0090 0%, #00fff9 100%)',
      gradientText: 'linear-gradient(90deg, #ff0090, #00fff9)',
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    emoji: '📄',
    folder: 'editorial',
    category: 'light',
    preview: ['#faf8f1', '#b5451b', '#2c4a1e'],
    fontHeading: 'Playfair Display',
    fontBody: 'Lora',
    colors: {
      bg: '#faf8f1',
      surface: '#f0ede2',
      surfaceHover: '#e8e4d4',
      primary: '#b5451b',
      primaryFg: '#ffffff',
      secondary: '#2c4a1e',
      accent: '#8b6914',
      text: '#1a1612',
      textMuted: '#5c4a3a',
      textSubtle: '#a08c76',
      border: '#d4ccbc',
      cardBg: '#f0ede2',
      gradient: 'linear-gradient(135deg, #b5451b 0%, #8b6914 100%)',
      gradientText: 'linear-gradient(90deg, #b5451b, #2c4a1e)',
    },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    emoji: '🌌',
    folder: 'neon-cyber',
    category: 'dark',
    preview: ['#05111a', '#00d4aa', '#9d4edd'],
    fontHeading: 'Space Grotesk',
    fontBody: 'Outfit',
    colors: {
      bg: '#05111a',
      surface: '#071e2c',
      surfaceHover: '#0a2a3c',
      primary: '#00d4aa',
      primaryFg: '#05111a',
      secondary: '#9d4edd',
      accent: '#ff6b6b',
      text: '#e8f4f8',
      textMuted: '#7eb8c8',
      textSubtle: '#2a5568',
      border: '#0d3348',
      cardBg: '#071e2c',
      gradient: 'linear-gradient(135deg, #00d4aa 0%, #9d4edd 100%)',
      gradientText: 'linear-gradient(90deg, #00d4aa, #9d4edd)',
    },
  },
  // ─── More Dark Pro ─────────────────────────────────────────────────────────────
  {
    id: 'carbon',
    name: 'Carbon',
    emoji: '🖤',
    folder: 'dark-pro',
    category: 'dark',
    preview: ['#161616', '#0f62fe', '#8a3ffc'],
    fontHeading: 'IBM Plex Sans',
    fontBody: 'IBM Plex Sans',
    colors: {
      bg: '#161616',
      surface: '#262626',
      surfaceHover: '#393939',
      primary: '#0f62fe',
      primaryFg: '#ffffff',
      secondary: '#8a3ffc',
      accent: '#00d0ff',
      text: '#f4f4f4',
      textMuted: '#a8a8a8',
      textSubtle: '#525252',
      border: '#393939',
      cardBg: '#262626',
      gradient: 'linear-gradient(135deg, #0f62fe 0%, #8a3ffc 100%)',
      gradientText: 'linear-gradient(90deg, #0f62fe, #00d0ff)',
    },
  },
  {
    id: 'eclipse',
    name: 'Eclipse',
    emoji: '🌒',
    folder: 'dark-pro',
    category: 'dark',
    preview: ['#12100e', '#fbbf24', '#f97316'],
    fontHeading: 'DM Mono',
    fontBody: 'Inter',
    colors: {
      bg: '#12100e',
      surface: '#1e1a15',
      surfaceHover: '#292319',
      primary: '#fbbf24',
      primaryFg: '#12100e',
      secondary: '#f97316',
      accent: '#ef4444',
      text: '#fef3c7',
      textMuted: '#d97706',
      textSubtle: '#78350f',
      border: '#292319',
      cardBg: '#1e1a15',
      gradient: 'linear-gradient(135deg, #fbbf24 0%, #f97316 100%)',
      gradientText: 'linear-gradient(90deg, #fbbf24, #ef4444)',
    },
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    emoji: '🌋',
    folder: 'dark-pro',
    category: 'dark',
    preview: ['#0c0c0c', '#6ee7b7', '#34d399'],
    fontHeading: 'Space Grotesk',
    fontBody: 'Inter',
    colors: {
      bg: '#0c0c0c',
      surface: '#161616',
      surfaceHover: '#1f1f1f',
      primary: '#6ee7b7',
      primaryFg: '#0c0c0c',
      secondary: '#34d399',
      accent: '#fbbf24',
      text: '#e5e7eb',
      textMuted: '#9ca3af',
      textSubtle: '#374151',
      border: '#1f2937',
      cardBg: '#161616',
      gradient: 'linear-gradient(135deg, #6ee7b7 0%, #34d399 100%)',
      gradientText: 'linear-gradient(90deg, #6ee7b7, #fbbf24)',
    },
  },
  // ─── More Light & Airy ───────────────────────────────────────────────────────
  {
    id: 'snow',
    name: 'Snow',
    emoji: '🌨️',
    folder: 'light',
    category: 'light',
    preview: ['#f0f9ff', '#0284c7', '#38bdf8'],
    fontHeading: 'Plus Jakarta Sans',
    fontBody: 'Inter',
    colors: {
      bg: '#f0f9ff',
      surface: '#ffffff',
      surfaceHover: '#e0f2fe',
      primary: '#0284c7',
      primaryFg: '#ffffff',
      secondary: '#0ea5e9',
      accent: '#7c3aed',
      text: '#0c4a6e',
      textMuted: '#0369a1',
      textSubtle: '#bae6fd',
      border: '#bae6fd',
      cardBg: '#ffffff',
      gradient: 'linear-gradient(135deg, #0284c7 0%, #38bdf8 100%)',
      gradientText: 'linear-gradient(90deg, #0284c7, #7c3aed)',
    },
  },
  {
    id: 'ivory',
    name: 'Ivory',
    emoji: '🏛️',
    folder: 'light',
    category: 'light',
    preview: ['#fffef7', '#ca8a04', '#92400e'],
    fontHeading: 'Cormorant Garamond',
    fontBody: 'Lora',
    colors: {
      bg: '#fffef7',
      surface: '#faf9f0',
      surfaceHover: '#f5f0e0',
      primary: '#ca8a04',
      primaryFg: '#ffffff',
      secondary: '#92400e',
      accent: '#15803d',
      text: '#1c1409',
      textMuted: '#713f12',
      textSubtle: '#d97706',
      border: '#fde68a',
      cardBg: '#faf9f0',
      gradient: 'linear-gradient(135deg, #ca8a04 0%, #92400e 100%)',
      gradientText: 'linear-gradient(90deg, #ca8a04, #92400e)',
    },
  },
  // ─── More Neon & Cyber ───────────────────────────────────────────────────────
  {
    id: 'neon',
    name: 'Neon',
    emoji: '🔆',
    folder: 'neon-cyber',
    category: 'dark',
    preview: ['#030a00', '#39ff14', '#ff00ff'],
    fontHeading: 'Share Tech Mono',
    fontBody: 'Share Tech Mono',
    colors: {
      bg: '#030a00',
      surface: '#0a1500',
      surfaceHover: '#112200',
      primary: '#39ff14',
      primaryFg: '#030a00',
      secondary: '#00ff88',
      accent: '#ff00ff',
      text: '#e0ffe0',
      textMuted: '#4dff4d',
      textSubtle: '#1a4d00',
      border: '#0d3300',
      cardBg: '#0a1500',
      gradient: 'linear-gradient(135deg, #39ff14 0%, #00ff88 100%)',
      gradientText: 'linear-gradient(90deg, #39ff14, #ff00ff)',
    },
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    emoji: '🌃',
    folder: 'neon-cyber',
    category: 'dark',
    preview: ['#0d0021', '#ff2d78', '#7b2fff'],
    fontHeading: 'Rajdhani',
    fontBody: 'Inter',
    colors: {
      bg: '#0d0021',
      surface: '#15003a',
      surfaceHover: '#1c0050',
      primary: '#ff2d78',
      primaryFg: '#ffffff',
      secondary: '#7b2fff',
      accent: '#00e5ff',
      text: '#ffe6f0',
      textMuted: '#c485b8',
      textSubtle: '#4d0080',
      border: '#2d0060',
      cardBg: '#15003a',
      gradient: 'linear-gradient(135deg, #ff2d78 0%, #7b2fff 100%)',
      gradientText: 'linear-gradient(90deg, #ff2d78, #00e5ff)',
    },
  },
  {
    id: 'matrix',
    name: 'Matrix',
    emoji: '🟩',
    folder: 'neon-cyber',
    category: 'dark',
    preview: ['#000800', '#00ff41', '#008f11'],
    fontHeading: 'Source Code Pro',
    fontBody: 'Source Code Pro',
    colors: {
      bg: '#000800',
      surface: '#001100',
      surfaceHover: '#001a00',
      primary: '#00ff41',
      primaryFg: '#000800',
      secondary: '#008f11',
      accent: '#00e5ff',
      text: '#00ff41',
      textMuted: '#008f11',
      textSubtle: '#003300',
      border: '#004400',
      cardBg: '#001100',
      gradient: 'linear-gradient(135deg, #00ff41 0%, #008f11 100%)',
      gradientText: 'linear-gradient(90deg, #00ff41, #00e5ff)',
    },
  },
  // ─── More Nature ─────────────────────────────────────────────────────────────
  {
    id: 'desert',
    name: 'Desert',
    emoji: '🏜️',
    folder: 'nature',
    category: 'light',
    preview: ['#fdf6e3', '#c2540a', '#d97706'],
    fontHeading: 'Lora',
    fontBody: 'Lora',
    colors: {
      bg: '#fdf6e3',
      surface: '#f5ead4',
      surfaceHover: '#eedfc0',
      primary: '#c2540a',
      primaryFg: '#ffffff',
      secondary: '#d97706',
      accent: '#7c3aed',
      text: '#292116',
      textMuted: '#78350f',
      textSubtle: '#a16207',
      border: '#f5d0a0',
      cardBg: '#f5ead4',
      gradient: 'linear-gradient(135deg, #c2540a 0%, #d97706 100%)',
      gradientText: 'linear-gradient(90deg, #c2540a, #d97706)',
    },
  },
  {
    id: 'sakura',
    name: 'Sakura',
    emoji: '🌸',
    folder: 'nature',
    category: 'light',
    preview: ['#fff0f6', '#e64980', '#f06595'],
    fontHeading: 'Plus Jakarta Sans',
    fontBody: 'Inter',
    colors: {
      bg: '#fff0f6',
      surface: '#ffffff',
      surfaceHover: '#ffd6e7',
      primary: '#e64980',
      primaryFg: '#ffffff',
      secondary: '#f06595',
      accent: '#7950f2',
      text: '#1a0a11',
      textMuted: '#862e5b',
      textSubtle: '#ffadd2',
      border: '#ffc9de',
      cardBg: '#ffffff',
      gradient: 'linear-gradient(135deg, #e64980 0%, #f06595 100%)',
      gradientText: 'linear-gradient(90deg, #e64980, #7950f2)',
    },
  },
  // ─── More Editorial ──────────────────────────────────────────────────────────
  {
    id: 'rose',
    name: 'Rose',
    emoji: '🌹',
    folder: 'editorial',
    category: 'light',
    preview: ['#fff1f2', '#e11d48', '#f43f5e'],
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    colors: {
      bg: '#fff1f2',
      surface: '#ffffff',
      surfaceHover: '#ffe4e6',
      primary: '#e11d48',
      primaryFg: '#ffffff',
      secondary: '#f43f5e',
      accent: '#9f1239',
      text: '#1c0a0f',
      textMuted: '#9f1239',
      textSubtle: '#fecdd3',
      border: '#fecdd3',
      cardBg: '#ffffff',
      gradient: 'linear-gradient(135deg, #e11d48 0%, #f43f5e 100%)',
      gradientText: 'linear-gradient(90deg, #e11d48, #9f1239)',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    emoji: '🪨',
    folder: 'editorial',
    category: 'light',
    preview: ['#f8fafc', '#475569', '#6366f1'],
    fontHeading: 'Inter',
    fontBody: 'Inter',
    colors: {
      bg: '#f8fafc',
      surface: '#f1f5f9',
      surfaceHover: '#e2e8f0',
      primary: '#475569',
      primaryFg: '#ffffff',
      secondary: '#334155',
      accent: '#6366f1',
      text: '#0f172a',
      textMuted: '#64748b',
      textSubtle: '#cbd5e1',
      border: '#e2e8f0',
      cardBg: '#ffffff',
      gradient: 'linear-gradient(135deg, #475569 0%, #334155 100%)',
      gradientText: 'linear-gradient(90deg, #475569, #6366f1)',
    },
  },
  // ─── Gradient ────────────────────────────────────────────────────────────────
  {
    id: 'candy',
    name: 'Candy',
    emoji: '🍭',
    folder: 'gradient',
    category: 'light',
    preview: ['#fdf4ff', '#c026d3', '#db2777'],
    fontHeading: 'Outfit',
    fontBody: 'Outfit',
    colors: {
      bg: '#fdf4ff',
      surface: '#fae8ff',
      surfaceHover: '#f5d0fe',
      primary: '#c026d3',
      primaryFg: '#ffffff',
      secondary: '#db2777',
      accent: '#7c3aed',
      text: '#1a0526',
      textMuted: '#86198f',
      textSubtle: '#e879f9',
      border: '#f0abfc',
      cardBg: '#fae8ff',
      gradient: 'linear-gradient(135deg, #c026d3 0%, #db2777 100%)',
      gradientText: 'linear-gradient(90deg, #c026d3, #7c3aed)',
    },
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    emoji: '🌌',
    folder: 'gradient',
    category: 'dark',
    preview: ['#0a0014', '#a855f7', '#ec4899'],
    fontHeading: 'Space Grotesk',
    fontBody: 'Outfit',
    colors: {
      bg: '#0a0014',
      surface: '#10001e',
      surfaceHover: '#1a0030',
      primary: '#a855f7',
      primaryFg: '#ffffff',
      secondary: '#6366f1',
      accent: '#ec4899',
      text: '#fdf4ff',
      textMuted: '#c084fc',
      textSubtle: '#2e1065',
      border: '#1e0040',
      cardBg: '#10001e',
      gradient: 'linear-gradient(135deg, #a855f7 0%, #ec4899 100%)',
      gradientText: 'linear-gradient(90deg, #a855f7, #ec4899)',
    },
  },
  {
    id: 'royal',
    name: 'Royal',
    emoji: '👑',
    folder: 'gradient',
    category: 'dark',
    preview: ['#0a0c1e', '#d4af37', '#b8960c'],
    fontHeading: 'Cormorant Garamond',
    fontBody: 'Inter',
    colors: {
      bg: '#0a0c1e',
      surface: '#0f1235',
      surfaceHover: '#151848',
      primary: '#d4af37',
      primaryFg: '#0a0c1e',
      secondary: '#b8960c',
      accent: '#c9b037',
      text: '#f0e8c8',
      textMuted: '#c9a227',
      textSubtle: '#2d2a00',
      border: '#2a2400',
      cardBg: '#0f1235',
      gradient: 'linear-gradient(135deg, #d4af37 0%, #b8960c 100%)',
      gradientText: 'linear-gradient(90deg, #d4af37, #c9b037)',
    },
  },
  {
    id: 'coral',
    name: 'Coral',
    emoji: '🪸',
    folder: 'gradient',
    category: 'light',
    preview: ['#fff5f5', '#ff6b6b', '#ee5a24'],
    fontHeading: 'Outfit',
    fontBody: 'Inter',
    colors: {
      bg: '#fff5f5',
      surface: '#ffffff',
      surfaceHover: '#ffe0e0',
      primary: '#ff6b6b',
      primaryFg: '#ffffff',
      secondary: '#ee5a24',
      accent: '#a29bfe',
      text: '#1a0a0a',
      textMuted: '#c0392b',
      textSubtle: '#ffb8b8',
      border: '#ffc9c9',
      cardBg: '#ffffff',
      gradient: 'linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%)',
      gradientText: 'linear-gradient(90deg, #ff6b6b, #a29bfe)',
    },
  },
];

export const getTheme = (id) => themes.find((t) => t.id === id) || themes[0];

export const loadThemeFonts = (theme) => {
  if (typeof document === 'undefined') return;
  const fontSet = new Set([theme.fontHeading, theme.fontBody].filter(Boolean));
  const families = Array.from(fontSet)
    .map((f) => `family=${f.replace(/ /g, '+')}:wght@300;400;500;600;700;800;900`)
    .join('&');
  const href = `https://fonts.googleapis.com/css2?${families}&display=swap`;
  let link = document.querySelector('#theme-fonts');
  if (!link) {
    link = document.createElement('link');
    link.id = 'theme-fonts';
    link.rel = 'stylesheet';
    document.head.appendChild(link);
  }
  link.href = href;
};

export const ThemeContext = createContext(themes[0]);
export const useTheme = () => useContext(ThemeContext);
